ui:
  port: ""
  image: icr.io/ai-services-cicd/catalog-ui:v0.0.4

backend:
  port: ""
  image: icr.io/ai-services-cicd/ai-services:0.0.9
  runtime: ""
  adminPasswordHash: ""
  podman:
    uri: "/run/podman/podman.sock"

db:
  port: ""
  image: icr.io/ai-services-private/postgres:18
  user: "admin"
  database: "ai_services"
  password: ""
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "1Gi"

caddy:
  image: "icr.io/ai-services-cicd/caddy:v2.11.2"
  # @description admin port for caddy. If unspecified, a random available port is assigned. Specify a port number to use a custom value.
  adminPort: ""
  # @description HTTPS port for caddy. Set by configure command via --https-port flag.
  httpsPort: ""
