FROM icr.io/ai-services-cicd/service-base:v0.0.28

WORKDIR /opt/services/chatbot

ENV PYTHONPATH=/opt/services

COPY common /opt/services/common
COPY chatbot/ .

RUN source /var/venv/bin/activate && pip install -r requirements.txt && pip cache purge

CMD ["/var/venv/bin/python", "-m", "uvicorn", "app:app", \
     "--host", "0.0.0.0", "--port", "5000", \
     "--loop", "uvloop", "--http", "httptools"]
