name: Digitize Service

on:
  push:
    paths:
      - 'services/digitize/**'
    branches:
      - main

jobs:
  build-publish-image:
    name: Build and Publish Image
    uses: ./.github/workflows/build-and-publish-image.yml
    with:
      service: 'digitize'
      working-directory: 'services'
    secrets: inherit

  scan:
    uses: ./.github/workflows/scanner.yml
    with:
      path: 'services'
      service: 'digitize'
      image: 'digitize-service'
    secrets:
      ICR_USERNAME: ${{ secrets.ICR_USERNAME }}
      ICR_APIKEY: ${{ secrets.ICR_APIKEY }}

# Made with Bob
