name: Scheduled CVE and Licenses Scan

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:
    inputs:
      skip-cves-scan:
        description: Skips cves scan job when variable is set to true.
        required: false
        type: boolean
        default: false
      skip-license-scan:
        description: Skips license scan job when variable is set to true.
        required: false
        type: boolean
        default: false

jobs:
  scan:
    strategy:
      fail-fast: false
      matrix:
        include:
         - path: images/caddy
           image: caddy
         - path: images/litellm
           image: litellm
         - path: images/postgres
           image: postgres
         - path: images/service-base
           image: service-base
         - path: images/tools
           image: tools
         - path: ui/catalog
           image: catalog-ui
         - path: ui/chatbot
           image: chatbot-ui
         - path: ui/digitize
           image: digitize-ui
         - path: services/chatbot
           image: chatbot-service
         - path: services/digitize
           image: digitize-service
         - path: services/similarity
           image: similarity-service
         - path: services/summarize
           image: summarize-service
         - path: ai-services
           image: ai-services
    uses: ./.github/workflows/scanner.yml
    with:
      path: ${{ matrix.path }}
      image: ${{ matrix.image }}
      skip-image-build: true
      ignore-unfixed: false
      skip-cves-scan: ${{ github.event_name == 'workflow_dispatch' && inputs.skip-cves-scan }}
      skip-license-scan: ${{ github.event_name == 'workflow_dispatch' && inputs.skip-license-scan }}
    secrets:
      ICR_USERNAME: ${{ secrets.ICR_USERNAME }}
      ICR_APIKEY: ${{ secrets.ICR_APIKEY }}
